Blog.create(author: 'John', title: 'John Blog', content: 'John blog content')
Blog.create(author: 'Peter', title: 'Peter Blog', content: 'Peter blog content')
Blog.create(author: 'Jack', title: 'Jack Blog', content: 'Jack blog content')
Blog.create(author: 'Ali', title: 'Ali Blog', content: 'Ali blog content')
Blog.create(author: 'Shahid', title: 'Shahid Blog', content: 'Shahid blog content')
